version: '3'
services:
  portafolio-app:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5006:5006"
    networks:
      - db_network
      - web_network
      
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 