# Generated by Django 3.0.1 on 2021-09-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=18)),
                ('primer_nom', models.CharField(max_length=55)),
                ('segundo_nom', models.CharField(max_length=55)),
                ('primer_ape', models.CharField(max_length=55)),
                ('segundo_ape', models.CharField(max_length=55)),
                ('biografia', models.TextField()),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('referencia', models.CharField(max_length=55)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blook.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=55)),
                ('cargo', models.CharField(max_length=55)),
                ('periodo_ini', models.IntegerField()),
                ('periodo_fin', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blook.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_institucion', models.CharField(max_length=55)),
                ('nom_carrera', models.CharField(max_length=55)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blook.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tecnologia', models.CharField(max_length=55)),
                ('porc_conoci', models.IntegerField()),
                ('ano_experi', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blook.Persona')),
            ],
        ),
    ]
