# Generated by Django 3.0.1 on 2021-09-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='periodo_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='periodo_ini',
            field=models.DateField(),
        ),
    ]
