# Generated by Django 3.0.1 on 2021-09-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0002_auto_20210905_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competencias',
            new_name='Competencia',
        ),
        migrations.RenameModel(
            old_name='RedesSociales',
            new_name='RedesSociale',
        ),
    ]
