# Generated by Django 3.0.1 on 2021-09-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0003_auto_20210905_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedesSociale',
            new_name='Redes_Sociale',
        ),
        migrations.RenameField(
            model_name='competencia',
            old_name='ano_experi',
            new_name='anos_experiencia',
        ),
        migrations.RenameField(
            model_name='competencia',
            old_name='nom_tecnologia',
            new_name='nombre_tecnologia',
        ),
        migrations.RenameField(
            model_name='competencia',
            old_name='porc_conoci',
            new_name='porcentaje_conocimiento',
        ),
        migrations.RenameField(
            model_name='educacion',
            old_name='nom_carrera',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='educacion',
            old_name='nom_institucion',
            new_name='nombre_institucion',
        ),
        migrations.RenameField(
            model_name='experiencia',
            old_name='periodo_ini',
            new_name='periodo_inicio',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='fechaNacimiento',
            new_name='fecha_Nacimiento',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_ape',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_nom',
            new_name='primer_nombre',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='segundo_ape',
            new_name='segundo_apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='segundo_nom',
            new_name='segundo_nombre',
        ),
    ]
