# Generated by Django 3.0.1 on 2021-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0004_auto_20210905_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='web',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
