# Generated by Django 3.0.1 on 2021-09-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0005_experiencia_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='biografia_Laboral',
            field=models.TextField(null=True),
        ),
    ]
