# Generated by Django 3.0.1 on 2021-09-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0006_persona_biografia_laboral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='biografia_Laboral',
            new_name='bio_Laboral',
        ),
    ]
