# Generated by Django 3.0.1 on 2021-09-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0007_auto_20210906_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='bio_Educacion',
            field=models.TextField(null=True),
        ),
    ]
