# Generated by Django 3.0.1 on 2021-09-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0009_persona_bio_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='ruta_logo',
            field=models.IntegerField(null=True),
        ),
    ]
