# Generated by Django 3.0.1 on 2021-09-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blook', '0010_educacion_ruta_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='bloke',
            field=models.IntegerField(null=True),
        ),
    ]
